/* ──────────────────────────────────────────────────────────────────────
   Clubtech branded landing — interactive booking-engine demo (#booking)

   Unbranded replica of the Clubtech booking product, rebuilt from live
   captures of the deployed engine (2026-07-13). Flow mirrors production:

     date modal → pan/zoom 3D map (zone pins, furniture hotspots)
       → furniture panel (chips, gallery, availability, packages)
       → cart w/ 10-min hold timer → add-ons (tabs, grid, featured)
       → order review (cart card, tax/fee summary) → guest details
       → demo confirmation (no payment, no network)

   Map art: assets/demo/venue-map.svg (deterministic, generated by
   scripts/build-venue-map.py — swap for a photoreal render anytime;
   hotspot coords are percentages of that image).

   Mount: <div id="product-demo" class="ckd"> in index.html.
   Analytics delegated to window.CTGTrack when present.
   ────────────────────────────────────────────────────────────────────── */

(function () {
  'use strict';

  var mounts = [].slice.call(document.querySelectorAll('[data-demo]'));
  if (!mounts.length) return;

  /* asset path relative to this script, so mounts work from any page depth */
  var SCRIPT_SRC = (document.currentScript && document.currentScript.src) || 'js/demo.js';
  var ASSET_BASE = SCRIPT_SRC.replace(/js\/demo\.js.*$/, 'assets/demo/');
  var MAP_URL = ASSET_BASE + 'venue-real.webp';
  var BRAND_MARK = SCRIPT_SRC.replace(/js\/demo\.js.*$/, 'brand/clubtech-mark-black-96.png');
  mounts.forEach(function (m) { createDemo(m); });

  function createDemo(root) {
  var OPTS = {
    view: root.getAttribute('data-demo') || 'map',
    badge: root.getAttribute('data-demo-badge') || '',
    mobile: root.getAttribute('data-demo-chrome') === 'mobile'
  };

  /* ===== demo data ==================================================== */

  var SPOTS = [
    { id: 'cab1', name: 'VIP Cabana', num: 12, zone: 'VIP Cabanas', x: 9.3, y: 13.3, w: 12.6, h: 13.8, cap: 8 },
    { id: 'cab2', name: 'VIP Cabana', num: 14, zone: 'VIP Cabanas', x: 9.3, y: 30.3, w: 12.6, h: 13.8, cap: 8, sold: true },
    { id: 'cab3', name: 'VIP Cabana', num: 16, zone: 'VIP Cabanas', x: 9.3, y: 47.3, w: 12.6, h: 13.8, cap: 8 },
    { id: 'cab4', name: 'VIP Cabana', num: 18, zone: 'VIP Cabanas', x: 9.3, y: 64.3, w: 12.6, h: 13.8, cap: 8, sold: true },
    { id: 'db1', name: 'Pool Club Bed', num: 651, zone: 'Pool Club', x: 37.5, y: 21.6, w: 4.0, h: 7.2, cap: 4 },
    { id: 'db2', name: 'Pool Club Bed', num: 652, zone: 'Pool Club', x: 43.9, y: 21.6, w: 4.0, h: 7.2, cap: 4, sold: true },
    { id: 'db3', name: 'Pool Club Bed', num: 653, zone: 'Pool Club', x: 50.3, y: 21.6, w: 4.0, h: 7.2, cap: 4 },
    { id: 'db4', name: 'Pool Club Bed', num: 654, zone: 'Pool Club', x: 56.7, y: 21.6, w: 4.0, h: 7.2, cap: 4, sold: true },
    { id: 'db5', name: 'Pool Club Bed', num: 655, zone: 'Pool Club', x: 62.2, y: 21.6, w: 4.0, h: 7.2, cap: 4 },
    { id: 'db6', name: 'Pool Club Bed', num: 656, zone: 'Pool Club', x: 36.2, y: 49.6, w: 3.9, h: 6.9, cap: 4, sold: true },
    { id: 'db7', name: 'Pool Club Bed', num: 657, zone: 'Pool Club', x: 42.7, y: 49.6, w: 3.9, h: 6.9, cap: 4 },
    { id: 'db8', name: 'Pool Club Bed', num: 658, zone: 'Pool Club', x: 49.9, y: 49.6, w: 3.9, h: 6.9, cap: 4 },
    { id: 'db9', name: 'Pool Club Bed', num: 659, zone: 'Pool Club', x: 56.6, y: 49.6, w: 3.9, h: 6.9, cap: 4, sold: true },
    { id: 'db10', name: 'Pool Club Bed', num: 660, zone: 'Pool Club', x: 63.6, y: 49.6, w: 3.9, h: 6.9, cap: 4 },
    { id: 'db11', name: 'Pool Club Bed', num: 661, zone: 'Pool Club', x: 26.6, y: 30.0, w: 4.6, h: 6.4, cap: 4, sold: true },
    { id: 'db12', name: 'Pool Club Bed', num: 662, zone: 'Pool Club', x: 26.6, y: 37.7, w: 4.6, h: 6.4, cap: 4 },
    { id: 'bb1', name: 'Beachfront Bale', num: 21, zone: 'Beachfront', x: 36.2, y: 61.0, w: 7.8, h: 10.4, cap: 6, sold: true },
    { id: 'bb2', name: 'Beachfront Bale', num: 22, zone: 'Beachfront', x: 44.9, y: 61.0, w: 7.8, h: 10.4, cap: 6 },
    { id: 'bb3', name: 'Beachfront Bale', num: 23, zone: 'Beachfront', x: 53.4, y: 61.0, w: 7.8, h: 10.4, cap: 6, sold: true },
    { id: 'bb4', name: 'Beachfront Bale', num: 24, zone: 'Beachfront', x: 64.1, y: 61.0, w: 7.8, h: 10.4, cap: 6, sold: true }
  ];

  var PINS = [
    { label: 'Pool Club', color: 'teal', icon: 'party', x: 48, y: 29 },
    { label: 'VIP Cabanas', color: 'pink', icon: 'party', x: 9.5, y: 7 },
    { label: 'Beachfront', color: 'pink', icon: 'party', x: 47, y: 67, sold: true },
    { label: 'Pool Bar', color: 'purple', icon: 'drink', x: 79.5, y: 21 },
    { label: 'Party Deck', color: 'purple', icon: 'drink', x: 81, y: 47 }
  ];

  var AREAS = [
    { label: 'Beach Access', x: 5, y: 78 },
    { label: 'Beach Access', x: 93, y: 76 },
    { label: 'Dance Floor', x: 81, y: 53 }
  ];

  var ZCARDS = [
    { status: 'Selling Fast', cls: 'fast', name: 'Pool Club' },
    { status: 'Selling Fast', cls: 'fast', name: 'VIP Cabanas' },
    { status: 'Sold Out', cls: 'sold', name: 'Beachfront' },
    { status: 'Sold Out', cls: 'sold', name: 'Sunset Deck' },
    { status: 'Sold Out', cls: 'sold', name: 'Party Pavilion' }
  ];

  var PKGS = [
    { id: 'bed', tab: 'Bed Only', name: 'Bed Only', price: 180, save: 40, arrive: 'Arrive Anytime',
      inc: [['ok', 'Flexible Arrival'], ['ok', '$120 in Food & Beverage Credit'], ['na', 'No Party Package Inclusions']] },
    { id: 'party', tab: 'Bed + Party Package', name: 'Bed + Party Package', price: 250, save: 70, arrive: 'Arrive Before 1pm', best: true,
      inc: [['na', 'No Flexible Arrival'], ['ok', '$150 in Food & Beverage Credit'], ['ok', '$100 in Party Package Value']] },
    { id: 'ult', tab: 'Ultimate Experience', name: 'Ultimate Experience', price: 680, save: 120, arrive: 'Arrive Anytime', gold: true,
      inc: [['ok', 'Flexible Arrival'], ['ok', '$300 in Food & Beverage Credit'], ['ok', 'Dedicated Host & Priority Entry']] }
  ];

  var ADDONS = [
    { id: 'rum', name: 'Signature White Rum', cat: 'Bottles', emoji: '🍾', bg: 'linear-gradient(160deg,#bfe6f2,#5db6d6)', img: 'addon-rum.jpg', video: 'video-rum.mp4', price: 118, was: 148, save: 'Save 20% online' },
    { id: 'gin', name: 'Island Botanical Gin', cat: 'Bottles', emoji: '🍸', bg: 'linear-gradient(160deg,#f6d8e8,#d67ab1)', img: 'addon-gin.jpg', video: 'video-gin.mp4', price: 118, was: 148, save: 'Save 20% online' },
    { id: 'bday', name: 'Birthday Package', cat: 'Special Occasions', emoji: '🎂', bg: 'linear-gradient(160deg,#ffe3c9,#f6a417)', img: 'addon-bday.jpg', price: 220, was: 275, save: 'Save 20% online' },
    { id: 'tira', name: 'Tiramisu', cat: 'Special Occasions', emoji: '🍰', bg: 'linear-gradient(160deg,#efe0d0,#c9a276)', img: 'addon-tira.jpg', price: 52 },
    { id: 'photo', name: 'Photo Package', cat: 'Experiences', emoji: '📸', bg: 'linear-gradient(160deg,#cfe8dc,#5fae8a)', img: 'addon-photo.jpg', price: 86 },
    { id: 'sushi', name: 'Japanese Sushi Boat', cat: 'Experiences', emoji: '🍣', bg: 'linear-gradient(160deg,#dbe3f5,#7e93cf)', img: 'addon-sushi.jpg', price: 154, was: 171, save: 'Save 10% online' }
  ];

  var SOCIAL = [
    { name: 'The Pavilion', img: 'social-pavilion.jpg', chips: [['free', '🔥 Free Entry'], ['ocean', '≋ Late Night']] },
    { name: 'Beach Party Bar', img: 'social-beachbar.jpg', chips: [['ocean', '≋ Oceanfront'], ['free', '🔥 Free Entry']] },
    { name: 'Surf Deck', img: 'social-surfdeck.jpg', chips: [['ocean', '≋ Oceanfront'], ['free', '🔥 Free Entry']] }
  ];

  var PROMOS = [
    { img: 'promo-vip.jpg', title: 'VIP Party Preview', sub: 'Pre-Opening Preview Sale', desc: 'Get 75% OFF the newest party experience before its official launch. Be among the first to get a sneak peek!' },
    { img: 'promo-happyhour.jpg', title: 'Daily Happy Hour', sub: '2 for 1 drinks!', desc: 'Daily from 8 PM to 9 PM' }
  ];

  var PASS = { name: 'Priority Entry Pass', price: 10, was: 40 };

  /* innerHTML-parsed <video autoplay muted> doesn't always start in Chrome —
     nudge playback explicitly */
  function nudgeVideo(scope) {
    $$('video', scope).forEach(function (vid) {
      vid.muted = true;
      var p = vid.play();
      if (p && p.catch) p.catch(function () {});
    });
  }

  function mediaBg(a) {
    return a.img
      ? 'background-image:url(' + ASSET_BASE + a.img + ');background-size:cover;background-position:center'
      : 'background:' + a.bg;
  }

  var MONTH = 'July 2026';
  var TODAY = 13;
  var WARN_DAYS = [13, 17, 18];   // almost sold out
  var TAX = 0.2, FEE = 9;

  /* ===== state ======================================================== */

  var state = {
    day: 18, pkg: 'party', spot: null, cart: [], addons: {}, pass: 0, addonTab: 'Bottles',
    shopSel: null, timer: 600, timerId: null, view: 'map', interacted: false
  };

  function track(n, p) { try { if (window.CTGTrack && window.CTGTrack.event) window.CTGTrack.event(n, p || {}); } catch (_) {} }
  function $(sel, el) { return (el || root).querySelector(sel); }
  function $$(sel, el) { return [].slice.call((el || root).querySelectorAll(sel)); }
  function money(n) { return '$' + n.toLocaleString('en-US'); }
  function h(tag, cls, html) { var n = document.createElement(tag); if (cls) n.className = cls; if (html != null) n.innerHTML = html; return n; }
  function dayLabel(d) { return ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][(d + 1) % 7]; } // 1 Jul 2026 = Wed
  function dateStr() { return state.day + ' July 2026'; }

  function subtotal() {
    var t = state.pass * PASS.price;
    state.cart.forEach(function (c) { t += c.price; });
    Object.keys(state.addons).forEach(function (id) {
      t += addon(id).price * state.addons[id];
    });
    return t;
  }
  function addon(id) { return ADDONS.filter(function (a) { return a.id === id; })[0]; }
  function grand() { var s = subtotal(); return s + Math.round(s * TAX) + (s ? FEE : 0); }
  function cartCount() { var n = state.cart.length + state.pass; Object.keys(state.addons).forEach(function (k) { n += state.addons[k]; }); return n; }

  /* ===== icons ======================================================== */

  var I = {
    logo: '<img src="' + BRAND_MARK + '" alt="">',
    cal: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3.5" y="5" width="17" height="15.5" rx="2.5"/><path d="M8 3v4M16 3v4M3.5 10h17"/></svg>',
    bed: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 18v-6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6M3 18h18M5 10V7a1.5 1.5 0 0 1 1.5-1.5h11A1.5 1.5 0 0 1 19 7v3"/></svg>',
    bag: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 8h14l-1 12.5H6L5 8Z"/><path d="M8.5 10V6.5a3.5 3.5 0 0 1 7 0V10"/></svg>',
    doc: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="3.5" width="14" height="17" rx="2"/><path d="M9 8.5h6M9 12h6M9 15.5h4"/></svg>',
    tick: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3.5" y="6" width="17" height="12" rx="2"/><path d="m8 12 2.5 2.5L16.5 9"/></svg>',
    cart: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9.5" cy="19.5" r="1.4"/><circle cx="17" cy="19.5" r="1.4"/><path d="M3.5 4.5h2l2 10.5h9.5l2-8H7"/></svg>',
    user: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8.5" r="3.5"/><path d="M5 20c1.2-3.4 3.8-5 7-5s5.8 1.6 7 5"/></svg>',
    clock: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/></svg>',
    party: '<svg viewBox="0 0 24 24" fill="#fff"><path d="M6 15.5 4 20l4.5-2L6 15.5Zm1.5-2.6 3.6 3.6 8.4-4.9a1 1 0 0 0 .1-1.6l-5.6-5.6a1 1 0 0 0-1.6.1L7.5 12.9ZM17 3.5l1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2Z"/></svg>',
    drink: '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="1.9"><path d="M5 5h14l-7 8v6M8.5 21h7M7 8h10"/></svg>',
    shopbag: '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="1.9"><path d="M5.5 8h13l-1 12h-11l-1-12Z"/><path d="M9 10V6.8a3 3 0 0 1 6 0V10"/></svg>',
    gem: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M7 4h10l4 5.5L12 21 3 9.5 7 4Z"/><path d="M3 9.5h18M9.5 4 12 21 14.5 4"/></svg>',
    pct: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="m9 15 6-6"/><circle cx="9.3" cy="9.3" r="1.1" fill="currentColor" stroke="none"/><circle cx="14.7" cy="14.7" r="1.1" fill="currentColor" stroke="none"/></svg>',
    ppl: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="9" r="3"/><path d="M3.5 19c.9-2.8 3-4.2 5.5-4.2s4.6 1.4 5.5 4.2M16 6.2a3 3 0 0 1 0 5.6M17.5 15c1.7.5 2.9 1.8 3.5 4"/></svg>',
    pax: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><circle cx="9" cy="8.5" r="3"/><path d="M3.5 19.5c1-3 3.1-4.5 5.5-4.5s4.5 1.5 5.5 4.5M15.5 6a3 3 0 0 1 0 5.4M17 15.4c1.8.6 3 2 3.7 4.1"/></svg>',
    google: '<svg viewBox="0 0 24 24"><path fill="#4285F4" d="M23.5 12.3c0-.9-.1-1.5-.3-2.2H12v4.1h6.5c-.1 1.1-.8 2.7-2.4 3.8l3.7 2.9c2.3-2.1 3.7-5.1 3.7-8.6Z"/><path fill="#34A853" d="M12 24c3.2 0 5.9-1.1 7.9-2.9l-3.7-2.9c-1 .7-2.4 1.2-4.2 1.2-3.2 0-5.9-2.1-6.8-5.1L1.3 17.2C3.3 21.2 7.3 24 12 24Z"/><path fill="#FBBC05" d="M5.2 14.3c-.2-.7-.4-1.5-.4-2.3s.1-1.6.4-2.3L1.3 6.8C.5 8.4 0 10.1 0 12s.5 3.6 1.3 5.2l3.9-2.9Z"/><path fill="#EA4335" d="M12 4.7c1.8 0 3 .8 3.7 1.4l3.3-3.2C17.9 1.1 15.2 0 12 0 7.3 0 3.3 2.8 1.3 6.8l3.9 2.9c.9-3 3.6-5 6.8-5Z"/></svg>',
    meta: '<svg viewBox="0 0 24 24" fill="#0082FB"><path d="M6.9 6.5c-2.8 0-5 3.3-5 7.4 0 2.6 1.2 4.2 3.1 4.2 1.4 0 2.4-.7 4.3-3.8l1.1-1.8.3.5 1 1.7c1.8 3 2.9 3.4 4.3 3.4 1.9 0 3.1-1.5 3.1-4.1 0-4.3-2.2-7.5-5-7.5-1.6 0-2.9.9-4.3 3-1.3-2-2.6-3-4.2-3Zm.2 2.4c.9 0 1.7.7 3 2.7l-1.3 2c-1.3 2-1.9 2.5-2.7 2.5-.8 0-1.3-.7-1.3-1.9 0-3 1.1-5.3 2.3-5.3Zm8 0c1.3 0 2.4 2.3 2.4 5.4 0 1.1-.4 1.8-1.2 1.8-.8 0-1.2-.5-2.6-2.7l-1.1-1.8c1.1-1.8 1.8-2.7 2.5-2.7Z"/></svg>'
  };

  function stepper(active) {
    var steps = [['Select Furniture', 'bed'], ['Add Ons', 'bag'], ['Order Review', 'doc'], ['Confirm', 'tick']];
    return steps.map(function (s, i) {
      return '<span class="' + (i === active ? 'on' : '') + '">' + I[s[1]] + '<u style="text-decoration:none">' + s[0] + '</u></span>' + (i < 3 ? '<i></i>' : '');
    }).join('');
  }

  /* ===== build shell ================================================== */

  var MAP = MAP_URL;
  var world, stage, hintEl;
  var Z = { s: 1, x: 0, y: 0 };

  function build() {
    root.innerHTML = '';
    root.style.backgroundImage = 'none';

    stage = h('div', 'ckd-stage');
    world = h('div', 'ckd-world');
    var wimg = world.appendChild(h('img'));
    wimg.alt = '';
    wimg.src = MAP;

    SPOTS.forEach(function (s) {
      var b = h('button', 'ckd-spot ' + (s.sold ? 'sold' : 'free'));
      b.type = 'button';
      b.style.cssText = 'left:' + s.x + '%;top:' + s.y + '%;width:' + s.w + '%;height:' + s.h + '%';
      b.setAttribute('data-id', s.id);
      b.setAttribute('aria-label', s.sold ? s.name + ' #' + s.num + ' — sold out' : 'Open ' + s.name + ' #' + s.num);
      if (s.sold) b.disabled = true;
      else b.addEventListener('click', function (e) { e.stopPropagation(); if (!suppressClick) openPanel(s); });
      world.appendChild(b);
    });

    PINS.forEach(function (p) {
      var el = h('div', 'ckd-pin ' + p.color,
        '<i>' + I[p.icon === 'party' ? 'party' : p.icon === 'drink' ? 'drink' : 'shopbag'] + '</i>' +
        '<div><em>' + p.label + '</em>' + (p.sold ? '<em class="soldchip">Sold Out</em>' : '') + '</div>');
      el.style.cssText = 'left:' + p.x + '%;top:' + p.y + '%';
      world.appendChild(el);
    });
    AREAS.forEach(function (a) {
      var el = h('div', 'ckd-area', a.label);
      el.style.cssText = 'left:' + a.x + '%;top:' + a.y + '%';
      world.appendChild(el);
    });

    stage.appendChild(world);
    root.appendChild(stage);

    // hint
    hintEl = h('div', 'ckd-hint', 'Live demo — tap a green spot to book it');
    root.appendChild(hintEl);

    // top chrome
    var top = h('div', 'ckd-top');
    var lg = h('button', 'ckd-logo', I.logo);
    lg.type = 'button';
    lg.setAttribute('aria-label', 'Back to booking map');
    lg.addEventListener('click', goMap);
    top.appendChild(lg);
    var dp = h('button', 'ckd-datepill', I.cal + '<span data-date>' + dateStr() + '</span>');
    dp.type = 'button';
    dp.addEventListener('click', function () { openModal(); });
    top.appendChild(dp);
    top.appendChild(h('div', 'ckd-stepper', stepper(0)));
    var cluster = h('div', 'ckd-cluster',
      '<span class="ckd-timer" data-timer>' + I.clock + '<span>10:00</span></span>' +
      '<button type="button" class="ckd-iconbtn" data-cartbtn aria-label="Cart">' + I.cart + '<b hidden>0</b></button>' +
      '<button type="button" class="ckd-iconbtn" data-userbtn aria-label="Account">' + I.user + '</button>');
    $('[data-cartbtn]', cluster).addEventListener('click', function () { openSheet('cart'); });
    $('[data-userbtn]', cluster).addEventListener('click', function () { openSheet('profile'); });
    top.appendChild(cluster);
    root.appendChild(top);

    // left rail (desktop) — items open the corresponding sheets
    var rail = h('div', 'ckd-rail',
      '<button type="button" data-sheet="queue"><span>' + I.gem + 'Skip The<br>Queue</span></button>' +
      '<button type="button" data-sheet="promos"><span>' + I.pct + 'Promotions</span></button>' +
      '<button type="button" data-sheet="zones"><span>' + I.ppl + 'Free Entry<br>Party Zones</span></button>');
    $$('[data-sheet]', rail).forEach(function (b) {
      b.addEventListener('click', function () { openSheet(b.getAttribute('data-sheet')); });
    });
    root.appendChild(rail);

    // zoom
    var zm = h('div', 'ckd-zoom', '<button type="button" aria-label="Zoom in">+</button><button type="button" aria-label="Zoom out">−</button>');
    zm.children[0].addEventListener('click', function () { zoomTo(Z.s * 1.35); });
    zm.children[1].addEventListener('click', function () { zoomTo(Z.s / 1.35); });
    root.appendChild(zm);

    // zone cards
    var zc = h('div', 'ckd-zones');
    var cards = h('div', 'ckd-zonecards');
    ZCARDS.forEach(function (z) {
      var c = h('button', 'ckd-zcard', '<small class="' + z.cls + '">' + z.status + '</small><strong>' + z.name + '</strong>');
      c.type = 'button';
      c.addEventListener('click', function () { focusZone(z.name); });
      cards.appendChild(c);
    });
    zc.appendChild(cards);
    var znext = zc.appendChild(h('button', 'ckd-znext', '›'));
    znext.type = 'button';
    znext.setAttribute('aria-label', 'More zones');
    znext.addEventListener('click', function () { cards.scrollBy({ left: 220, behavior: 'smooth' }); });
    root.appendChild(zc);

    // booking bar
    var bar = h('div', 'ckd-bar');
    root.appendChild(bar);
    renderBar();

    if (OPTS.mobile) {
      root.classList.add('mobile');
      root.appendChild(h('span', 'ckd-flytimer', I.clock + '<span>10:00</span>')).setAttribute('data-timer', '');
      var tb = h('div', 'ckd-tabbar',
        '<button type="button" data-sheet="queue">' + I.gem + 'Skip The Queue</button>' +
        '<button type="button" data-sheet="promos">' + I.pct + 'Promotions</button>' +
        '<button type="button" data-sheet="zones">' + I.ppl + 'Free Entry Party Zones</button>');
      $$('[data-sheet]', tb).forEach(function (b) {
        b.addEventListener('click', function () { openSheet(b.getAttribute('data-sheet')); });
      });
      root.appendChild(tb);
    }

    // bottom sheets
    var scrimEl = h('div', 'ckd-sheetscrim');
    scrimEl.addEventListener('click', closeSheet);
    root.appendChild(scrimEl);
    root.appendChild(h('div', 'ckd-sheet'));

    // overlays
    root.appendChild(buildModal());
    root.appendChild(h('div', 'ckd-panel'));
    ['addons', 'review', 'confirm', 'success'].forEach(function (v) {
      var el = h('div', 'ckd-view');
      el.setAttribute('data-view', v);
      root.appendChild(el);
    });

    initPanZoom();

    function sizeMode() {
      root.classList.toggle('narrow', root.clientWidth < 760);
      root.classList.toggle('tiny', root.clientWidth < 460);
    }
    sizeMode();
    if (window.ResizeObserver) new ResizeObserver(sizeMode).observe(root);
  }

  function mark() {
    if (state.interacted) return;
    state.interacted = true;
    hintEl.classList.add('off');
    track('demo_interact', {});
  }

  /* ===== pan / zoom ==================================================== */

  var MAP_AR = 1536 / 1152; // aspect ratio of the venue render

  /* stage layout size in CSS px — clientWidth/Height ignore ancestor
     transforms (reveal animations), which getBoundingClientRect does not;
     a rect measured mid-animation left the world sized for a shrunken
     stage and the hotspots adrift of the art */
  function stageSize() {
    return { width: stage.clientWidth, height: stage.clientHeight };
  }

  function sizeWorld() {
    var r = stageSize();
    if (!r.width || !r.height) return;
    var w = Math.max(r.width, r.height * MAP_AR);
    var h = w / MAP_AR;
    if (h < r.height) { h = r.height; w = h * MAP_AR; }
    // only touch the DOM when the size actually changed
    if (Math.abs(w - (world._w || 0)) < 1 && Math.abs(h - (world._h || 0)) < 1) return;
    world._w = w; world._h = h;
    world.style.width = w + 'px';
    world.style.height = h + 'px';
  }

  function apply() {
    // self-heal: any stale world (measured mid-animation / pre-CSS) is
    // corrected on the next pan/zoom/tap instead of persisting
    sizeWorld();
    var r = stageSize();
    if (!world._w) return;
    var ww = world._w * Z.s, wh = world._h * Z.s;
    Z.x = Math.min(0, Math.max(r.width - ww, Z.x));
    Z.y = Math.min(0, Math.max(r.height - wh, Z.y));
    world.style.transform = 'translate(' + Z.x + 'px,' + Z.y + 'px) scale(' + Z.s + ')';
    $$('.ckd-pin', world).concat($$('.ckd-area', world)).forEach(function (p) {
      p.style.transformOrigin = '0 50%';
      p.style.transform = 'translate(-15px,-50%) scale(' + (1 / Z.s) + ')';
    });
  }

  function zoomTo(s, cx, cy) {
    mark();
    var r = stageSize();
    cx = cx == null ? r.width / 2 : cx; cy = cy == null ? r.height / 2 : cy;
    var ns = Math.min(3.2, Math.max(1, s));
    var k = ns / Z.s;
    Z.x = cx - k * (cx - Z.x); Z.y = cy - k * (cy - Z.y); Z.s = ns;
    apply();
  }

  function focusZone(name) {
    mark();
    var map = { 'Pool Club': [48, 30], 'VIP Cabanas': [11, 34], 'Beachfront': [47, 62], 'Sunset Deck': [81, 47], 'Party Pavilion': [79, 22] };
    var t = map[name] || [50, 50];
    sizeWorld();
    var r = stageSize();
    Z.s = 1.9;
    Z.x = r.width / 2 - t[0] / 100 * world._w * Z.s;
    Z.y = r.height / 2 - t[1] / 100 * world._h * Z.s;
    apply();
    track('demo_zone_focus', { zone: name });
  }

  var suppressClick = false;

  function initPanZoom() {
    var down = null;
    stage.addEventListener('pointerdown', function (e) {
      down = { x: e.clientX, y: e.clientY, ox: Z.x, oy: Z.y, moved: false };
      stage.classList.add('drag');
    });
    window.addEventListener('pointermove', function (e) {
      if (!down) return;
      var dx = e.clientX - down.x, dy = e.clientY - down.y;
      if (Math.abs(dx) + Math.abs(dy) > 5) { down.moved = true; mark(); }
      if (!down.moved) return;
      Z.x = down.ox + dx; Z.y = down.oy + dy;
      apply();
    });
    window.addEventListener('pointerup', function () {
      if (down && down.moved) {
        suppressClick = true;
        setTimeout(function () { suppressClick = false; }, 0);
      }
      down = null;
      stage.classList.remove('drag');
    });
    stage.addEventListener('wheel', function (e) {
      e.preventDefault();
      var r = stage.getBoundingClientRect();
      zoomTo(Z.s * (e.deltaY < 0 ? 1.12 : 0.89), e.clientX - r.left, e.clientY - r.top);
    }, { passive: false });
    sizeWorld();
    // center the (possibly wider-than-frame) world
    var r0 = stageSize();
    Z.x = (r0.width - world._w) / 2;
    Z.y = (r0.height - world._h) / 2;
    apply();
    if (window.ResizeObserver) new ResizeObserver(function () { sizeWorld(); apply(); }).observe(stage);
    // late layout settles (fonts, first paint, reveal animations) can shift
    // sizes without a resize event — re-sync on load and on a few timers
    window.addEventListener('load', function () { sizeWorld(); apply(); });
    [300, 1200, 3000].forEach(function (t) { setTimeout(function () { sizeWorld(); apply(); }, t); });
  }

  /* ===== date modal ==================================================== */

  function buildModal() {
    var scrim = h('div', 'ckd-scrim');
    var m = h('div', 'ckd-modal');
    var days = '', d = 1;
    var rows = [[null, null, 0, 0, 0, 0, 0]]; // 1 Jul 2026 = Wed
    // build calendar cells: July 2026, starts Wed, 31 days
    var cells = [];
    for (var i = 0; i < 2; i++) cells.push(null);
    for (d = 1; d <= 31; d++) cells.push(d);
    while (cells.length % 7) cells.push(null);
    var rowsHtml = '';
    for (var r = 0; r < cells.length / 7; r++) {
      rowsHtml += '<tr>';
      for (var c = 0; c < 7; c++) {
        var v = cells[r * 7 + c];
        if (v == null) { rowsHtml += '<td></td>'; continue; }
        var past = v < TODAY;
        var dot = past ? '' : WARN_DAYS.indexOf(v) !== -1 ? '<span class="dot warn"></span>' : '<span class="dot promo"></span>';
        rowsHtml += '<td><button type="button" class="ckd-day' + (past ? ' past' : '') + (v === state.day ? ' sel' : '') + '" data-day="' + v + '">' + v + '</button>' + dot + '</td>';
      }
      rowsHtml += '</tr>';
    }
    m.innerHTML =
      '<button type="button" class="ckd-x" aria-label="Close">✕</button>' +
      '<h3 role="presentation">Select Date</h3>' +
      '<div class="ckd-monthrow"><button type="button">‹</button><b>' + MONTH + '</b><button type="button">›</button></div>' +
      '<table class="ckd-cal"><thead><tr><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th><th>Sun</th></tr></thead>' +
      '<tbody>' + rowsHtml + '</tbody></table>' +
      '<div class="ckd-legend">' +
        '<p><i style="background:#f26d7e"></i>Almost Sold Out</p>' +
        '<p><i style="background:#7c3aed"></i>Promo Available</p>' +
      '</div>' +
      '<div class="ckd-modal-foot"><button type="button" class="ckd-btn-ghost" data-cancel>Cancel</button>' +
      '<button type="button" class="ckd-btn-dark" data-choose>Choose Bed</button></div>';
    scrim.appendChild(m);

    $('.ckd-x', m).addEventListener('click', closeModal);
    $('[data-cancel]', m).addEventListener('click', closeModal);
    $('[data-choose]', m).addEventListener('click', function () { closeModal(); track('demo_date_chosen', { day: state.day }); });
    $$('.ckd-day', m).forEach(function (b) {
      b.addEventListener('click', function () {
        state.day = +b.getAttribute('data-day');
        $$('.ckd-day.sel', m).forEach(function (x) { x.classList.remove('sel'); });
        b.classList.add('sel');
        $$('[data-date]').forEach(function (x) { x.textContent = dateStr(); });
      });
    });
    scrim.addEventListener('click', function (e) { if (e.target === scrim) closeModal(); });
    return scrim;
  }

  function openModal() { mark(); $('.ckd-scrim').classList.add('open'); track('demo_date_open', {}); }
  function closeModal() { $('.ckd-scrim').classList.remove('open'); }

  /* ===== furniture panel ============================================== */

  var curSpot = null;

  function galleryTile(s, zoomPct, i) {
    var scenic = [[s.x, s.y], [56, 30], [46, 63], [12, 42], [86, 42]];
    return 'background-position:' + scenic[i][0] + '% ' + scenic[i][1] + '%';
  }

  function openPanel(s) {
    mark();
    curSpot = s;
    state.pkg = 'party';
    var p = $('.ckd-panel');
    p.innerHTML =
      '<div class="ckd-panel-scroll">' +
        '<button type="button" class="ckd-x" aria-label="Close">✕</button>' +
        '<h2 role="presentation">' + s.name + ' – #' + s.num + '</h2>' +
        '<div class="ckd-chiprow">' +
          '<span class="ckd-chip blue">✦ New</span>' +
          '<span class="ckd-chip pinkc">🎉 Party Zone</span>' +
          '<span class="ckd-chip grey">Ground Floor</span>' +
        '</div>' +
        '<p class="ckd-pax">' + I.pax + ' Recommended for ' + s.cap + ' People <em>· Adults Only (16+)</em></p>' +
        '<p class="ckd-desc">A lively spot at the heart of the club — great music, cold bottles, and a front-row seat to the best energy on the coast.</p>' +
        '<div class="ckd-gallery">' +
          '<div style="' + galleryTile(s, 300, 0) + '"><span class="play"><i>▶</i></span></div>' +
          [1, 2, 3, 4].map(function (i) { return '<div style="' + galleryTile(s, 520, i) + '"></div>'; }).join('') +
        '</div>' +
        '<h4 role="presentation" class="ckd-h4">Next Availability</h4>' +
        '<div class="ckd-days">' +
          [16, 17, 18, 19, 20].map(function (d) {
            return '<button type="button" data-day="' + d + '" class="' + (d === state.day ? 'sel' : '') + '"><b>' + d + '</b><small>Jul</small><span>' + dayLabel(d) + '</span></button>';
          }).join('') +
          '<span class="cal">' + I.cal + '</span>' +
        '</div>' +
        '<h4 role="presentation" class="ckd-save">Book Online &amp; Save</h4><p>Packages</p>' +
        '<div class="ckd-pkgtabs">' +
          PKGS.map(function (k) { return '<button type="button" data-pkgtab="' + k.id + '" class="' + (k.gold ? 'gold ' : '') + (k.id === state.pkg ? 'on' : '') + '">' + k.tab + '</button>'; }).join('') +
        '</div>' +
        '<div class="ckd-pkgs">' +
          PKGS.map(function (k) {
            return '<div class="ckd-pkg' + (k.id === state.pkg ? ' sel' : '') + '" data-pkg="' + k.id + '">' +
              (k.best ? '<span class="best">Best Value</span>' : '') +
              '<span class="savechip">Book Online &amp; Save <b>' + money(k.save) + '</b></span>' +
              '<h5 role="presentation">' + k.name + '<i>✓</i></h5>' +
              '<p class="price">' + money(k.price) + '</p>' +
              '<p class="arrive">' + k.arrive + '</p>' +
              '<ul>' + k.inc.map(function (x) { return '<li class="' + x[0] + '"><i>' + (x[0] === 'ok' ? '✓' : '·') + '</i>' + x[1] + '</li>'; }).join('') + '</ul>' +
              '<span class="more">See Package Inclusions ⌄</span>' +
            '</div>';
          }).join('') +
        '</div>' +
      '</div>' +
      '<div class="ckd-panel-foot">' +
        '<small>Includes $150 in food &amp; beverage credit</small>' +
        '<div><button type="button" class="ckd-btn-line" data-addcart>Add to Cart ' + I.cart + '</button>' +
        '<button type="button" class="ckd-cta" data-booknow style="flex:1.2">Book Now</button></div>' +
      '</div>';

    $('.ckd-x', p).addEventListener('click', closePanel);
    $$('[data-day]', p).forEach(function (b) {
      b.addEventListener('click', function () {
        state.day = +b.getAttribute('data-day');
        $$('.ckd-days button', p).forEach(function (x) { x.classList.toggle('sel', x === b); });
        $$('[data-date]').forEach(function (x) { x.textContent = dateStr(); });
      });
    });
    function selectPkg(id) {
      state.pkg = id;
      $$('[data-pkgtab]', p).forEach(function (t) { t.classList.toggle('on', t.getAttribute('data-pkgtab') === id); });
      $$('[data-pkg]', p).forEach(function (c) { c.classList.toggle('sel', c.getAttribute('data-pkg') === id); });
    }
    $$('[data-pkgtab]', p).forEach(function (t) { t.addEventListener('click', function () { selectPkg(t.getAttribute('data-pkgtab')); }); });
    $$('[data-pkg]', p).forEach(function (c) { c.addEventListener('click', function () { selectPkg(c.getAttribute('data-pkg')); }); });
    $('[data-addcart]', p).addEventListener('click', function () { addToCart(s); closePanel(); });
    $('[data-booknow]', p).addEventListener('click', function () { addToCart(s); closePanel(); showView('addons'); });

    p.classList.add('open');
    track('demo_spot_view', { spot: s.id });
  }

  function closePanel() { $('.ckd-panel').classList.remove('open'); }

  /* ===== cart & timer ================================================= */

  function addToCart(s) {
    if (state.cart.some(function (c) { return c.spot === s.id; })) { renderBar(); return; }
    var pkg = PKGS.filter(function (k) { return k.id === state.pkg; })[0];
    state.cart.push({ spot: s.id, name: s.name + ' #' + s.num, pkg: pkg.name, price: pkg.price, arrive: pkg.arrive, cap: s.cap, x: s.x, y: s.y });
    $('[data-id="' + s.id + '"]').classList.add('picked');
    startTimer();
    renderBar();
    track('demo_add_to_cart', { spot: s.id, pkg: pkg.id });
  }

  function startTimer() {
    if (state.timerId) return;
    state.timer = 600;
    var els = function () { return $$('[data-timer]'); };
    els().forEach(function (t) { t.classList.add('show'); });
    state.timerId = setInterval(function () {
      state.timer = Math.max(0, state.timer - 1);
      var m = Math.floor(state.timer / 60), s = ('0' + state.timer % 60).slice(-2);
      $$('[data-timer] span:last-child').forEach(function (x) { x.textContent = m + ':' + s; });
      if (!state.timer) { clearInterval(state.timerId); state.timerId = null; }
    }, 1000);
  }

  function renderBar() {
    var bar = $('.ckd-bar');
    var badge = $('[data-cartbtn] b');
    if (badge) { badge.textContent = cartCount(); badge.hidden = !cartCount(); }
    root.classList.toggle('has-cart', !!state.cart.length);
    if (!state.cart.length) {
      bar.innerHTML = '';
      bar.style.display = 'none';
    } else {
      bar.style.display = '';
      var c = state.cart[state.cart.length - 1];
      bar.innerHTML = '<span class="ckd-thumb" style="background-image:url(' + MAP + ');background-position:' + c.x + '% ' + c.y + '%"></span>' +
        '<p>Total<b>' + money(subtotal()) + '</b></p>' +
        '<button type="button" class="ckd-cta" data-go>Book Now</button>';
      $('[data-go]', bar).addEventListener('click', function () { showView('addons'); });
    }
  }

  /* ===== views ======================================================== */

  function goMap() {
    closeSheet();
    closePanel();
    closeModal();
    showView('map');
    sizeWorld();
    apply();
  }

  function appbar(step) {
    return '<div class="ckd-appbar">' +
      '<button type="button" class="ckd-logo" data-home aria-label="Back to booking map">' + I.logo + '</button>' +
      '<div class="ckd-stepper" style="flex:1;justify-content:center">' + stepper(step) + '</div>' +
      '<div class="ckd-cluster">' +
        '<span class="ckd-timer' + (state.timerId ? ' show' : '') + '" data-timer>' + I.clock + '<span>–:––</span></span>' +
        '<button type="button" class="ckd-iconbtn" data-vcart>' + I.cart + '<b ' + (cartCount() ? '' : 'hidden') + '>' + cartCount() + '</b></button>' +
        '<button type="button" class="ckd-iconbtn" data-vuser aria-label="Account">' + I.user + '</button>' +
      '</div></div>';
  }

  function showView(name) {
    mark();
    $$('.ckd-view').forEach(function (v) { v.classList.remove('open'); });
    if (name === 'map') return;
    var v = $('[data-view="' + name + '"]');
    if (name === 'addons') renderAddons(v);
    if (name === 'review') renderReview(v);
    if (name === 'confirm') renderConfirm(v);
    if (name === 'success') renderSuccess(v);
    v.classList.add('open');
    track('demo_view', { view: name });
  }

  function wireAppbar(v) {
    var c = $('[data-vcart]', v);
    if (c) c.addEventListener('click', function () { openSheet('cart'); });
    var u = $('[data-vuser]', v);
    if (u) u.addEventListener('click', function () { openSheet('profile'); });
    var hm = $('[data-home]', v);
    if (hm) hm.addEventListener('click', goMap);
  }

  function renderAddons(v) {
    if (OPTS.mobile || root.clientWidth < 600) return renderShop(v);
    var cats = ['Bottles', 'Special Occasions', 'Experiences'];
    var list = ADDONS.filter(function (a) { return a.cat === state.addonTab; });
    var feat = list[0];
    v.innerHTML = appbar(1) +
      '<div class="ckd-body"><h2 role="presentation">Add Ons</h2>' +
      '<div class="ckd-tabs">' + cats.map(function (c) { return '<button type="button" data-tab="' + c + '" class="' + (c === state.addonTab ? 'on' : '') + '">' + c + '</button>'; }).join('') + '</div>' +
      '<div class="ckd-addon-cols">' +
        '<div class="ckd-addon-grid">' +
          list.map(function (a) {
            var q = state.addons[a.id] || 0;
            return '<div class="ckd-prod"><div class="ph" style="' + mediaBg(a) + '">' + (a.img ? '' : a.emoji) +
              (a.save ? '<span class="flame">🔥 ' + a.save + '</span>' : '') + '</div>' +
              '<div class="info"><h5 role="presentation">' + a.name + '</h5><span class="tag">' + a.cat + '</span>' +
              '<div class="prices">' + (a.was ? '<s>' + money(a.was) + '</s>' : '') + '<b>' + money(a.price) + '</b></div>' +
              '<button type="button" class="ckd-btn-line' + (q ? ' added' : '') + '" data-add="' + a.id + '">' + (q ? '✓ Added (' + q + ')' : 'Add to Cart ') + (q ? '' : I.cart) + '</button></div></div>';
          }).join('') +
        '</div>' +
        '<div class="ckd-feature" style="' + mediaBg(feat) + '">' +
          (feat.video
            ? '<video class="featvid" autoplay muted loop playsinline src="' + ASSET_BASE + feat.video + '"></video>'
            : (feat.img ? '' : '<span class="big">' + feat.emoji + '</span>')) +
          '<h4 role="presentation">' + feat.name + '</h4>' + (feat.was ? '<s>' + money(feat.was) + '</s>' : '') +
          '<p class="fp">' + money(feat.price) + '</p>' + (feat.save ? '<span class="savechip">' + feat.save + '</span>' : '') +
          '<button type="button" data-add="' + feat.id + '">Add to Cart ' + I.cart + '</button>' +
        '</div>' +
      '</div></div>' +
      '<div class="ckd-foot">' +
        '<button type="button" class="back" data-back>Back</button>' +
        '<div class="tot"><span class="ckd-thumb"></span><p>Grand Total<b>' + money(grand()) + '</b></p></div>' +
        '<button type="button" class="ckd-cta" data-checkout>Checkout</button>' +
      '</div>';
    wireAppbar(v);
    nudgeVideo(v);
    $$('[data-tab]', v).forEach(function (t) {
      t.addEventListener('click', function () { state.addonTab = t.getAttribute('data-tab'); renderAddons(v); });
    });
    $$('[data-add]', v).forEach(function (b) {
      b.addEventListener('click', function () {
        var id = b.getAttribute('data-add');
        state.addons[id] = (state.addons[id] || 0) + 1;
        track('demo_addon_add', { addon: id });
        renderAddons(v); renderBar();
      });
    });
    $('[data-back]', v).addEventListener('click', function () { showView('map'); });
    $('[data-checkout]', v).addEventListener('click', function () { showView('review'); });
  }

  /* mobile add-ons — full-screen shop: full-bleed product media, category
     tabs over the top, scrollable inventory rail on the right, price block
     bottom-left, add-to-cart / checkout dock (mirrors the live product) */
  function renderShop(v) {
    var cats = ['Bottles', 'Special Occasions', 'Experiences'];
    var list = ADDONS.filter(function (a) { return a.cat === state.addonTab; });
    if (!state.shopSel || !list.some(function (a) { return a.id === state.shopSel; })) state.shopSel = list[0].id;
    var sel = addon(state.shopSel);
    v.innerHTML =
      '<div class="ckd-shop">' +
        (sel.video
          ? '<video class="media" autoplay muted loop playsinline' + (sel.img ? ' poster="' + ASSET_BASE + sel.img + '" style="' + mediaBg(sel) + '"' : '') + ' src="' + ASSET_BASE + sel.video + '"></video>'
          : '<div class="media" style="' + mediaBg(sel) + '"></div>') +
        '<div class="ckd-shop-top">' +
          '<button type="button" class="ckd-shop-back" data-back aria-label="Back to map">‹</button>' +
          '<span class="ckd-shop-timer' + (state.timerId ? ' show' : '') + '" data-timer>' + I.clock + '<span>–:––</span></span>' +
          '<button type="button" class="ckd-shop-iconbtn" data-vcart aria-label="Cart">' + I.cart + '<b ' + (cartCount() ? '' : 'hidden') + '>' + cartCount() + '</b></button>' +
          '<button type="button" class="ckd-shop-iconbtn" data-vuser aria-label="Account">' + I.user + '</button>' +
        '</div>' +
        '<div class="ckd-shop-tabs">' +
          cats.map(function (c) { return '<button type="button" data-tab="' + c + '" class="' + (c === state.addonTab ? 'on' : '') + '">' + c + '</button>'; }).join('') +
        '</div>' +
        '<div class="ckd-shop-rail">' +
          list.map(function (a) {
            var on = a.id === state.shopSel;
            return '<button type="button" class="ckd-shop-thumb' + (on ? ' on' : '') + '" data-sel="' + a.id + '">' +
              '<span>' + a.name + '</span><i style="' + mediaBg(a) + '">' + (a.img ? '' : a.emoji) + '</i></button>';
          }).join('') +
        '</div>' +
        '<div class="ckd-shop-info">' +
          '<h3 role="presentation">' + sel.name + '</h3>' +
          (sel.was ? '<s>' + money(sel.was) + '</s>' : '') +
          '<p class="p">' + money(sel.price) + '</p>' +
          (sel.save ? '<span class="savechip">' + sel.save + '</span>' : '') +
        '</div>' +
        '<div class="ckd-shop-dock">' +
          '<div class="tot"><span>Total</span><b>' + money(grand()) + '</b></div>' +
          '<div class="btns">' +
            '<button type="button" class="add" data-add="' + sel.id + '">Add to Cart ' + I.cart + '</button>' +
            '<button type="button" class="co" data-checkout>Checkout</button>' +
          '</div>' +
        '</div>' +
      '</div>';
    nudgeVideo(v);
    $$('[data-tab]', v).forEach(function (t) {
      t.addEventListener('click', function () { state.addonTab = t.getAttribute('data-tab'); state.shopSel = null; renderShop(v); });
    });
    $$('[data-sel]', v).forEach(function (b) {
      b.addEventListener('click', function () { state.shopSel = b.getAttribute('data-sel'); renderShop(v); });
    });
    $('[data-add]', v).addEventListener('click', function () {
      var id = sel.id;
      state.addons[id] = (state.addons[id] || 0) + 1;
      track('demo_addon_add', { addon: id });
      renderShop(v); renderBar();
    });
    $('[data-back]', v).addEventListener('click', function () { showView('map'); });
    $('[data-checkout]', v).addEventListener('click', function () { showView('review'); });
    $('[data-vcart]', v).addEventListener('click', function () { openSheet('cart'); });
    $('[data-vuser]', v).addEventListener('click', function () { openSheet('profile'); });
  }

  function renderReview(v) {
    var recs = ADDONS.filter(function (a) { return !state.addons[a.id]; }).slice(0, 3);
    var sub = subtotal(), tax = Math.round(sub * TAX);
    v.innerHTML = appbar(2) +
      '<div class="ckd-body"><h2 role="presentation">Order Review</h2>' +
      '<div class="ckd-datebar">' + I.cal + '<span>Booking Date: <b data-date>' + dateStr() + '</b></span></div>' +
      '<div class="ckd-review-cols">' +
        '<div><h4 role="presentation" class="ckd-h6">Recommended For Your Booking</h4>' +
          '<div class="ckd-banner">' + I.pct + ' Last Chance To Get Up To 30% Off Bottles</div>' +
          '<div class="ckd-recs">' + recs.map(function (a) {
            return '<div class="ckd-rec"><div class="ph" style="' + mediaBg(a) + '">' + (a.img ? '' : a.emoji) + '</div>' +
              '<div class="info"><h6 role="presentation">' + a.name + '</h6><p>' + money(a.price) + '</p></div></div>';
          }).join('') + '</div>' +
        '</div>' +
        '<div class="ckd-cartcard"><h4 role="presentation">Your Cart</h4><p class="lbl">Furniture</p>' +
          state.cart.map(function (c, i) {
            return '<div class="ckd-item"><span class="ckd-thumb" style="background-position:' + c.x + '% ' + c.y + '%"></span>' +
              '<div style="flex:1"><h6 role="presentation">' + c.name + '<br>' + c.pkg + '</h6>' +
              '<p>' + I.clock + ' ' + c.arrive + '</p>' +
              '<p>' + I.pax + ' Recommended for ' + c.cap + ' People</p>' +
              '<p>$150 food &amp; beverage credit</p>' +
              '<div class="pr">' + money(c.price) + '</div></div>' +
              '<button type="button" class="rm" data-rm="' + i + '" aria-label="Remove">✕</button></div>';
          }).join('') +
          Object.keys(state.addons).map(function (id) {
            var a = addon(id);
            return '<div class="ckd-item"><span class="ckd-thumb" style="' + (a.img ? mediaBg(a) : 'background-image:none;background:' + a.bg + ';display:grid;place-items:center;font-size:24px') + '">' + (a.img ? '' : a.emoji) + '</span>' +
              '<div style="flex:1"><h6 role="presentation">' + a.name + ' × ' + state.addons[id] + '</h6>' +
              '<div class="pr">' + money(a.price * state.addons[id]) + '</div></div>' +
              '<button type="button" class="rm" data-rma="' + id + '" aria-label="Remove">✕</button></div>';
          }).join('') +
          '<button type="button" class="ckd-addmore" data-more>Book Additional Furniture +</button>' +
          '<div class="ckd-sums">' +
            '<div class="ckd-sumrow"><span>Subtotal</span><b>' + money(sub) + '</b></div>' +
            '<div class="ckd-sumrow"><span>20% Government Tax &amp;<br>Service Charge</span><b>' + money(tax) + '</b></div>' +
            '<div class="ckd-sumrow"><span>Processing Fee</span><b>' + money(sub ? FEE : 0) + '</b></div>' +
            '<div class="ckd-sumrow grand"><span><b>Grand Total</b></span><b>' + money(grand()) + '</b></div>' +
          '</div>' +
          '<button type="button" class="ckd-checkoutbtn" data-proceed>Proceed to Checkout</button>' +
        '</div>' +
      '</div></div>';
    wireAppbar(v);
    $$('[data-rm]', v).forEach(function (b) {
      b.addEventListener('click', function () {
        var c = state.cart.splice(+b.getAttribute('data-rm'), 1)[0];
        if (c) { var sp = $('[data-id="' + c.spot + '"]'); if (sp) sp.classList.remove('picked'); }
        if (!state.cart.length) { showView('map'); } else renderReview(v);
        renderBar();
      });
    });
    $$('[data-rma]', v).forEach(function (b) {
      b.addEventListener('click', function () { delete state.addons[b.getAttribute('data-rma')]; renderReview(v); renderBar(); });
    });
    $('[data-more]', v).addEventListener('click', function () { showView('map'); });
    $('[data-proceed]', v).addEventListener('click', function () { showView('confirm'); });
  }

  function renderConfirm(v) {
    v.innerHTML = appbar(3) +
      '<div class="ckd-body"><div class="ckd-form">' +
        '<h2 role="presentation">Tell us more about you</h2>' +
        '<div class="ckd-frow">' +
          '<label class="ckd-field"><span>First Name</span><input placeholder="First Name" autocomplete="off"></label>' +
          '<label class="ckd-field"><span>Last Name</span><input placeholder="Last Name" autocomplete="off"></label>' +
        '</div>' +
        '<label class="ckd-field"><span>Email</span><input placeholder="Email" autocomplete="off"></label>' +
        '<label class="ckd-field"><span>Phone Number</span><div class="ckd-phone">' +
          '<span class="cc">🌴 +62 ▾</span><input placeholder="Enter Phone Number" autocomplete="off" style="flex:1"></div></label>' +
        '<button type="button" class="ckd-continue" data-done>Continue</button>' +
        '<div class="ckd-or">Or fill with</div>' +
        '<div class="ckd-sso"><button type="button" aria-label="Continue with Google">' + I.google + '</button>' +
        '<button type="button" aria-label="Continue with Meta">' + I.meta + '</button></div>' +
      '</div></div>';
    wireAppbar(v);
    $$('.ckd-sso button', v).forEach(function (b) { b.addEventListener('click', function () { showView('success'); }); });
    $('[data-done]', v).addEventListener('click', function () {
      track('demo_confirm', { total: grand(), spots: state.cart.length });
      showView('success');
    });
  }

  function renderSuccess(v) {
    v.innerHTML = appbar(3) +
      '<div class="ckd-success">' +
        '<i>✓</i><h3 role="presentation">Booking confirmed</h3>' +
        '<p>' + dateStr() + ' is locked in — the spot is off the market and the revenue is banked before doors open.</p>' +
        '<span class="tag">Interactive demo · no payment taken</span>' +
        '<button type="button" class="ckd-cta" data-restart>Start over</button>' +
      '</div>';
    $('[data-restart]', v).addEventListener('click', function () {
      state.cart = []; state.addons = {}; state.day = 18;
      if (state.timerId) { clearInterval(state.timerId); state.timerId = null; }
      $$('.ckd-spot.picked').forEach(function (s) { s.classList.remove('picked'); });
      $$('[data-timer]').forEach(function (t) { t.classList.remove('show'); });
      $$('[data-date]').forEach(function (x) { x.textContent = dateStr(); });
      renderBar();
      showView('map');
      track('demo_restart', {});
    });
  }


  /* ===== bottom sheets (cart / queue / promos / zones) ================ */

  function closeSheet() {
    $('.ckd-sheet').classList.remove('open');
    $('.ckd-sheetscrim').classList.remove('open');
  }

  function sheetShell(titleHtml, bodyHtml, footHtml) {
    return '<div class="ckd-sheet-head">' + titleHtml +
      '<button type="button" class="ckd-x" aria-label="Close">✕</button></div>' +
      '<div class="ckd-sheet-body">' + bodyHtml + '</div>' +
      (footHtml ? '<div class="ckd-sheet-foot">' + footHtml + '</div>' : '');
  }

  function openSheet(name) {
    mark();
    var s = $('.ckd-sheet');
    if (name === 'zones') {
      s.innerHTML = sheetShell('<h3 role="presentation">Free Entry Party Zones</h3>',
        '<p class="ckd-social-copy">Several social areas where you can walk in for free and enjoy with no minimum spend. Grab a drink at the bar and take in the oceanfront views and sunsets — world-class entertainment and parties every day of the week!</p>' +
        '<div class="ckd-socialrow">' + SOCIAL.map(function (z) {
          return '<div class="ckd-social" style="background-image:url(' + ASSET_BASE + z.img + ')">' +
            z.chips.map(function (c) { return '<span class="chip ' + c[0] + '">' + c[1] + '</span>'; }).join('') +
            '<strong>' + z.name + '</strong></div>';
        }).join('') + '</div>');
    }
    if (name === 'queue') {
      s.innerHTML = sheetShell('<h3 role="presentation">Skip The Queue</h3>',
        '<div class="ckd-qbanner"><span class="off">⊘ 75% OFF</span>' +
        '<h5 role="presentation">You got 75% OFF for booking in advance</h5>' +
        '<p>You\u2019re all set with the best price for your day.</p></div>' +
        '<div class="ckd-qdays"><h4 role="presentation">Choose Date</h4><div class="ckd-days">' +
        [16, 17, 18, 19, 20].map(function (d) {
          return '<button type="button" data-qday="' + d + '" class="' + (d === state.day ? 'sel' : '') + '"><b>' + d + '</b><small>Jul</small><span>' + dayLabel(d) + '</span></button>';
        }).join('') + '</div></div>' +
        '<div class="ckd-qtotal"><span>Total</span><span><s>' + money(PASS.was) + '</s><b>' + money(PASS.price) + '</b></span></div>' +
        '<button type="button" class="ckd-qbook' + (state.pass ? ' added' : '') + '" data-qbook>' + (state.pass ? '✓ Priority Entry added' : 'Book Now') + '</button>');
      $$('[data-qday]', s).forEach(function (b) {
        b.addEventListener('click', function () {
          state.day = +b.getAttribute('data-qday');
          $$('[data-qday]', s).forEach(function (x) { x.classList.toggle('sel', x === b); });
          $$('[data-date]').forEach(function (x) { x.textContent = dateStr(); });
        });
      });
      $('[data-qbook]', s).addEventListener('click', function () {
        if (!state.pass) {
          state.pass = 1;
          startTimer();
          renderBar();
          track('demo_priority_pass', {});
        }
        openSheet('cart');
      });
    }
    if (name === 'profile') {
      s.innerHTML = sheetShell('<h3 role="presentation" class="center">Account</h3>',
        '<div class="ckd-acct">' +
          '<span class="av">' + I.user + '</span>' +
          '<h6 role="presentation">You’re browsing as a guest</h6>' +
          '<p>Sign in to see your bookings and check out faster.</p>' +
          '<div class="ckd-sso"><button type="button" aria-label="Continue with Google">' + I.google + '</button>' +
          '<button type="button" aria-label="Continue with Meta">' + I.meta + '</button></div>' +
        '</div>' +
        '<div class="ckd-acct-rows">' +
          '<button type="button" data-acct="bookings">' + I.doc + '<span>My Bookings</span><i>›</i></button>' +
          '<button type="button">' + I.tick + '<span>Payment Methods</span><i>›</i></button>' +
          '<button type="button">' + I.ppl + '<span>Help &amp; Support</span><i>›</i></button>' +
        '</div>');
      $('[data-acct="bookings"]', s).addEventListener('click', function () { openSheet('cart'); });
    }
    if (name === 'promos') {
      s.innerHTML = sheetShell('<h3 role="presentation">Promotions</h3>',
        PROMOS.map(function (p) {
          return '<div class="ckd-promo"><span class="th" style="background-image:url(' + ASSET_BASE + p.img + ')"></span>' +
            '<div><h6 role="presentation">' + p.title + '</h6><p class="sub">' + p.sub + '</p><p>' + p.desc + '</p></div>' +
            '<span class="chev">›</span></div>';
        }).join(''));
    }
    if (name === 'cart') {
      var items = '';
      state.cart.forEach(function (c, i) {
        items += '<div class="ckd-cartitem"><span class="th" style="background-position:' + c.x + '% ' + c.y + '%"></span>' +
          '<div style="flex:1"><h6 role="presentation">' + c.name + '<br>' + c.pkg + '</h6>' +
          '<p>' + I.clock + ' ' + c.arrive + '</p><p>' + I.pax + ' Recommended for ' + c.cap + ' People</p>' +
          '<div class="pr">' + money(c.price) + '</div></div>' +
          '<button type="button" class="rm" data-rmf="' + i + '" aria-label="Remove">✕</button></div>';
      });
      Object.keys(state.addons).forEach(function (id) {
        var a = addon(id);
        items += '<div class="ckd-cartitem"><span class="th" style="' + (a.img ? 'background-image:url(' + ASSET_BASE + a.img + ');background-size:cover;background-position:center' : 'background:' + a.bg) + '"></span>' +
          '<div style="flex:1"><h6 role="presentation">' + a.name + ' × ' + state.addons[id] + '</h6>' +
          '<div class="pr">' + money(a.price * state.addons[id]) + '</div></div>' +
          '<button type="button" class="rm" data-rmc="' + id + '" aria-label="Remove">✕</button></div>';
      });
      if (state.pass) {
        items += '<div class="ckd-cartitem"><span class="th" style="background-image:none;background:linear-gradient(160deg,#7ce8c8,#0d7a56);display:grid;place-items:center;font-size:26px">🎟</span>' +
          '<div style="flex:1"><h6 role="presentation">' + PASS.name + '</h6><p>' + I.gem.replace('currentColor', '#0d7a56') + ' Skip the line · 75% off booked ahead</p>' +
          '<div class="pr"><s style="color:#9b9b9b;font-weight:500;font-size:11px;margin-right:6px">' + money(PASS.was) + '</s>' + money(PASS.price) + '</div></div>' +
          '<button type="button" class="rm" data-rmp aria-label="Remove">✕</button></div>';
      }
      var empty = !items;
      s.innerHTML = sheetShell('<h3 role="presentation" class="center">Cart</h3>',
        '<div class="ckd-cart-date"><span>' + I.cal + ' ' + state.day + ' Jul</span></div>' +
        (empty
          ? '<div class="ckd-cart-empty">' +
            '<svg viewBox="0 0 24 24" fill="none" stroke="#1c1c1c" stroke-width="1.1"><circle cx="9.5" cy="19.5" r="1.3" fill="#1c1c1c"/><circle cx="16.5" cy="19.5" r="1.3" fill="#1c1c1c"/><path d="M4 5h2l2 10h9l2-7.5H7.2" stroke-linejoin="round"/></svg>' +
            '<h6 role="presentation">Your cart is empty</h6><p>Let\u2019s change that!</p></div>'
          : items),
        empty
          ? '<button type="button" class="ckd-booknow" data-explore>Explore Furnitures</button>'
          : '<button type="button" class="ckd-morebtn" data-more2>Book More Furniture +</button>' +
            '<button type="button" class="ckd-booknow" data-cartbook>Book Now</button>');
      var ex = $('[data-explore]', s);
      if (ex) ex.addEventListener('click', function () { closeSheet(); showView('map'); });
      var mb = $('[data-more2]', s);
      if (mb) mb.addEventListener('click', function () { closeSheet(); showView('map'); });
      var bn = $('[data-cartbook]', s);
      if (bn) bn.addEventListener('click', function () { closeSheet(); showView('addons'); });
      $$('[data-rmf]', s).forEach(function (b) {
        b.addEventListener('click', function () {
          var c = state.cart.splice(+b.getAttribute('data-rmf'), 1)[0];
          if (c) { var sp = $('[data-id="' + c.spot + '"]'); if (sp) sp.classList.remove('picked'); }
          renderBar(); openSheet('cart');
        });
      });
      $$('[data-rmc]', s).forEach(function (b) {
        b.addEventListener('click', function () { delete state.addons[b.getAttribute('data-rmc')]; renderBar(); openSheet('cart'); });
      });
      var rp = $('[data-rmp]', s);
      if (rp) rp.addEventListener('click', function () { state.pass = 0; renderBar(); openSheet('cart'); });
    }
    $('.ckd-x', s).addEventListener('click', closeSheet);
    $('.ckd-sheetscrim').classList.add('open');
    s.classList.add('open');
    track('demo_sheet', { sheet: name });
  }

  window.addEventListener('keydown', function (e) {
    if (e.key !== 'Escape') return;
    if ($('.ckd-scrim.open')) closeModal();
    else if ($('.ckd-sheet.open')) closeSheet();
    else if ($('.ckd-panel.open')) closePanel();
  });

  build();

  /* ===== initial state per mount ==================================== */

  function seedCart(withAddon) {
    var s = SPOTS.filter(function (x) { return x.id === 'db10'; })[0];
    var pkg = PKGS[1];
    state.cart.push({ spot: s.id, name: s.name + ' #' + s.num, pkg: pkg.name, price: pkg.price, arrive: pkg.arrive, cap: s.cap, x: s.x, y: s.y });
    var sb = $('[data-id="' + s.id + '"]');
    if (sb) sb.classList.add('picked');
    if (withAddon) state.addons.rum = 1;
    startTimer();
    renderBar();
  }

  (function init() {
    var bhost = h('div', 'demo-badge-host');
    root.parentNode.insertBefore(bhost, root);
    bhost.appendChild(root);
    if (OPTS.badge) {
      bhost.appendChild(h('div', 'ckd-badge' + (OPTS.view === 'panel' ? ' right' : ''), '<i></i>' + OPTS.badge));
    }
    bhost.appendChild(hintEl);
    var v = OPTS.view;
    if (v === 'map') return;
    hintEl.classList.add('off');
    state.interacted = true;
    if (v === 'datemodal') { $('.ckd-scrim').classList.add('open'); return; }
    if (v === 'panel') {
      openPanel(SPOTS.filter(function (x) { return x.id === 'db3'; })[0]);
      return;
    }
    if (v === 'addons') { seedCart(false); showView('addons'); }
    if (v === 'review') { seedCart(true); showView('review'); }
    if (v === 'confirm') { seedCart(true); showView('confirm'); }
    if (v === 'success') { seedCart(true); showView('success'); }
  })();
  }
})();
